# Generated by Django 5.1.3 on 2024-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
    ]
