# Generated by Django 5.1.3 on 2024-12-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='picture',
            new_name='image',
        ),
    ]
