# Generated by Django 5.1.3 on 2024-12-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='picture',
            new_name='image',
        ),
    ]
