# Generated by Django 5.1.3 on 2024-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_picture_update_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
