# Generated by Django 5.1.3 on 2024-12-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='picture',
            new_name='image',
        ),
    ]
