# Generated by Django 5.1.3 on 2024-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_picture_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='yo', unique=True),
        ),
    ]
