# Generated by Django 5.1.3 on 2024-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateField(auto_now_add=True)),
                ('company', models.CharField(default='', max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=4096)),
            ],
        ),
    ]
