# Generated by Django 5.1.3 on 2024-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
