# Generated by Django 5.1.3 on 2024-12-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_alter_message_company'),
        ('pricing', '0004_alter_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.offer'),
        ),
        migrations.AddField(
            model_name='message',
            name='requested_quote',
            field=models.BooleanField(default=False),
        ),
    ]
